# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

baseURL = "https://sorairolake.github.io/blog/"
copyright = "Shun Sakai"
defaultContentLanguage = "ja"
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true
languageCode = "ja"
title = "SorairoLake's Blog"
