# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

description = "SorairoLakeの個人ブログ"
mainSections = ["posts"]

[dateFormat]
published = ":date_full"
lastUpdated = ":date_full"

[sidebar]
emoji = "🐧"
subtitle = "書きたいと思ったことを適当に書きます"

[sidebar.avatar]
src = "https://sorairolake.github.io/images/profile.svg"

[footer]
since = 2021

[article]
math = true
toc = true

[article.license]
enabled = true
default = "この記事は[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)の下でライセンスされています"

[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "sorairolake/blog"
repoID = "R_kgDOGmszOQ"
category = "Announcements"
categoryID = "DIC_kwDOGmszOc4C2Lez"
mapping = "pathname"
strict = 0
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "top"
lightTheme = "light"
darkTheme = "dark_dimmed"
lang = "ja"
loading = "lazy"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[[widgets.homepage]]
type = "categories"

[[widgets.homepage]]
type = "tag-cloud"

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = "sorairolake"
card = "summary"

[defaultImage.opengraph]
enabled = true
src = "images/ogp.webp"
local = true
