baseURL = "https://sorairolake.github.io/blog/"
copyright = "&copy; 2021 Shun Sakai &middot; Licensed under the [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/)"
defaultContentLanguage = "ja"
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true
languageCode = "ja"
theme = "PaperMod"
title = "SorairoLake's blog"

[[menu.main]]
identifier = "category"
name = "カテゴリ"
url = "/categories/"

[[menu.main]]
identifier = "tag"
name = "タグ"
url = "/tags/"

[params]
author = "Shun Sakai"
ShowPostNavLinks = true
ShowReadingTime = true

[params.homeInfoParams]
Content = "Welcome to my blog!"
Title = "SorairoLake's blog"

[[params.socialIcons]]
name = "github"
url = "https://github.com/sorairolake"

[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/sorairolake"

[taxonomies]
category = "categories"
tag = "tags"
