# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

baseURL = "https://sorairolake.github.io/blog/"
copyright = """\
  &copy; 2021&ndash;2024 Shun Sakai \
  &middot; \
  [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)\
  """
defaultContentLanguage = "ja"
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true
languageCode = "ja"
theme = "PaperMod"
title = "SorairoLake's Blog"

[[menu.main]]
name = "アーカイブ"
url = "/archive/"
weight = 10

[[menu.main]]
name = "カテゴリ"
url = "/categories/"
weight = 20

[[menu.main]]
name = "検索"
url = "/search/"
weight = 30

[[menu.main]]
name = "タグ"
url = "/tags/"
weight = 40

[[menu.main]]
name = "ホームページ"
url = "https://sorairolake.github.io/"
weight = 50

[[menu.main]]
name = "このブログについて"
url = "/about-blog/"
weight = 60

[outputs]
home = ["HTML", "JSON", "RSS"]

[params]
description = "SorairoLakeのブログ。"
author = "Shun Sakai"
DateFormat = "2006-01-02"
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
showtoc = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "SorairoLake's Blog"
Content = "Welcome to my blog!"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/sorairolake"

[[params.socialIcons]]
name = "mastodon"
url = "https://misskey.io/@sorairolake"

[[params.socialIcons]]
name = "github"
url = "https://github.com/sorairolake"

[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/sorairolake"

[taxonomies]
category = "categories"
tag = "tags"
